# This is a basic workflow to help you get started with Actions

name: Deploy to server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: deploy to raspberry pi
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd co2tracker/ && bash update-api.sh
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: co2tracker
          password : ${{ secrets.PASSWORD }}

      - name: sleep a little
        run: sleep 5
        
      - name: check if server is running
        run: echo "::set-output name=RESP_CODE::$(curl -I -s https://co2.dcronqvist.se | grep -o 200 -c)"
        id: check-run
      
      - name: fail if no 200 status
        if: ${{ steps.check-run.outputs.RESP_CODE == 1 }}
        run: echo "All went well, server is up and running."
